version: '3'

services:
  generator:
    networks:
      - service-net
    image: p4elll/flash_cards_generator:latest
    ports:
      - 8082:8082
    env_file:
      - .env
  auth:
    networks:
      - service-net
    image: p4elll/auth_nate_service:latest
    ports:
      - 8081:8081
    env_file:
      - .env
  nginx:
    networks:
      - service-net
    image: nginx:latest
    ports:
      - "80:80"
      - "443:80"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certs/letsencrypt/archive/nate-ai.com/fullchain1.pem:/etc/letsencrypt/live/nate-ai.com/fullchain.pem
      - ./certs/letsencrypt/archive/nate-ai.com/privkey1.pem:/etc/letsencrypt/live/nate-ai.com/privkey.pem
    restart: always
    env_file:
      - .env
networks:
  service-net:
    driver: bridge
