name: Deployment

on:
  workflow_dispatch:

jobs:
  restart-docker-compose:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: Install SSH client
        run: sudo apt-get install -y ssh 

      - name: Restart Docker Compose
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@178.128.47.82 'cd ~/apps/nate_main && docker-compose down'
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@178.128.47.82 'cd ~/apps/nate_main && git fetch && git rebase'
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@178.128.47.82 'cd ~/apps/nate_main && docker-compose pull && docker-compose up -d'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

